config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "welcome#index"
  resources :mensagens do
    collection do
      get 'enviadas'
    end
  end
  get "/welcome", to: "welcome#index"

  get 'users/index'
  get 'users/show'


  #Routes do Sistema de Estágio
  get 'estagio_welcome/locus'

  get 'estagio_welcome/index'
  post 'estagio_welcome/index'

  get 'estagio_welcome/pendente'
  post 'estagio_welcome/pendente'

  get 'estagio_welcome/edit'
  post 'estagio_welcome/edit'

  get 'estagio_welcome/update'
  post 'estagio_welcome/update'

  get 'estagio_welcome/historico'
  post 'estagio_welcome/historico'

  get 'estagio_welcome/status_impressao'
  post 'estagio_welcome/status_impressao'

  get 'estagio_welcome/pdf_visualiza'

  get 'relatorio_centro/index'
  
  get 'relatorio_aditivocentro/index'

  get 'relatorio_campiaditivo/index'

  get 'relatorio_estadualaditivo/index'

  get 'relatorio_municipalouparticularaditivo/index'

  get 'relatorio_campi/index'

  get 'relatorio_publico/index'

  get 'carta_apresentacao/index'
  get 'carta_apresentacao/edit'

  get 'carta_apresentacao/create'
  post 'carta_apresentacao/create'

  get 'carta_apresentacao/edit'
  post 'carta_apresentacao/edit'

  get 'carta_apresentacao/update'
  post 'carta_apresentacao/update'

  get 'relatorio_particular/index'
  get 'relatorio_particular/edit'

  get 'relatorio_particular/update'
  post 'relatorio_particular/update'

  get 'relatorio_particular/create'
  post 'relatorio_particular/create'

  get 'relatorio_naoformal/index'
  get 'relatorio_naoformal/edit'

  get 'relatorio_naoformal/create'
  post 'relatorio_naoformal/create'

  get 'relatorio_naoformal/edit'
  post 'relatorio_naoformal/edit'

  get 'relatorio_naoformal/update'
  post 'relatorio_naoformal/update'

  get 'relatorio_centro/create'
  post 'relatorio_centro/create'

  get 'relatorio_centro/edit'
  post 'relatorio_centro/edit'

  get 'relatorio_aditivocentro/create'
  post 'relatorio_aditivocentro/create'

  get 'relatorio_aditivocentro/edit'
  post 'relatorio_aditivocentro/edit'

  get 'relatorio_aditivocentro/update'
  post 'relatorio_aditivocentro/update'

  get 'relatorio_campiaditivo/create'
  post 'relatorio_campiaditivo/create'

  get 'relatorio_campiaditivo/edit'
  post 'relatorio_campiaditivo/edit'

  get 'relatorio_estadualaditivo/create'
  post 'relatorio_estadualaditivo/create'

  get 'relatorio_estadualaditivo/edit'
  post 'relatorio_estadualaditivo/edit'

  get 'relatorio_estadualaditivo/update'
  post 'relatorio_estadualaditivo/update'

  get 'relatorio_centro/update'
  post 'relatorio_centro/update'

  get 'relatorio_municipalouparticularaditivo/update'
  post 'relatorio_municipalouparticularaditivo/update'

  get 'relatorio_municipalouparticularaditivo/create'
  post 'relatorio_municipalouparticularaditivo/create'

  get 'relatorio_municipalouparticularaditivo/edit'
  post 'relatorio_municipalouparticularaditivo/edit'

  get 'relatorio_campi/create'
  post 'relatorio_campi/create'

  get 'relatorio_campi/edit'
  post 'relatorio_campi/edit'

  get 'relatorio_campi/update'
  post 'relatorio_campi/update'

  get 'relatorio_publico/create'
  post 'relatorio_publico/create'

  get 'relatorio_publico/edit'
  post 'relatorio_publico/edit'

  get 'relatorio_publico/update'
  post 'relatorio_publico/update'

 
  get 'pdf_geral/carta_apresentacao'
  get 'pdf_geral/particular'
  get 'pdf_geral/publico'
  get 'pdf_geral/centro'
  get 'pdf_geral/campi'
  get 'pdf_geral/naoformal'
  get 'pdf_geral/publico'
  get 'pdf_geral/aditivocentro'
  get 'pdf_geral/campiaditivo'
  get 'pdf_geral/estadualaditivo'
  get 'pdf_geral/municipalouparticularaditivo'

  get 'pdf_geral/update_aditivocentro'
  post 'pdf_geral/update_aditivocentro'

  get 'pdf_geral/update_campiaditivo'
  post 'pdf_geral/update_campiaditivo'

  get 'pdf_geral/update_estadualaditivo'
  post 'pdf_geral/update_estadualaditivo'

  get 'pdf_geral/update_municipalouparticularaditivo'
  post 'pdf_geral/update_municipalouparticularaditivo'
  
  get 'pdf_geral/update_particular'
  post 'pdf_geral/update_particular'

  get 'pdf_geral/update_publico'
  post 'pdf_geral/update_publico'

  get 'pdf_geral/update_carta'
  post 'pdf_geral/update_carta'

  get 'pdf_geral/update_centro'
  post 'pdf_geral/update_centro'

  get 'pdf_geral/update_campi'
  post 'pdf_geral/update_campi'

  get 'pdf_geral/update_naoformal'
  post 'pdf_geral/update_naoformal'

  #delete cartaapresentacao
  get 'delete_carta_apresentacao/:user_id', to: 'carta_apresentacao#destroy', as: 'delete_carta_apresentacao'
  #get 'delete_carta_apresentacao/delete_by_matricula/:matricula_aluno', to: 'carta_apresentacao#destroy_by_matricula', as: 'delete_carta_by_matricula'

  #deletes relats
  get '/delete_relat_centro/:user_id', to: 'relatorio_centro#destroy', as: 'delete_relat_centro'
  get '/delete_relat_campi/:user_id', to: 'relatorio_campi#destroy', as: 'delete_relat_campi'
  get '/delete_relat_publico/:user_id', to: 'relatorio_publico#destroy', as: 'delete_relat_publico'
  get '/delete_relat_particular/:user_id', to: 'relatorio_particular#destroy', as: 'delete_relat_particular'
  get '/delete_relat_aditivocentro/:user_id', to: 'relatorio_aditivocentro#destroy', as: 'delete_relat_aditivocentro'
  get '/delete_relat_campiaditivo/:user_id', to: 'relatorio_campiaditivo#destroy', as: 'delete_relat_campiaditivo'
  get '/delete_relat_estadualaditivo/:user_id', to: 'relatorio_estadualaditivo#destroy', as: 'delete_relat_estadualaditivo'
  get '/delete_relat_municipalouparticularaditivo/:user_id', to: 'relatorio_municipalouparticularaditivo#destroy', as: 'delete_relat_municipalouparticularaditivo'


  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords' }
  
 resources :users do
  member do
    get 'liberar'
   end
end

resources :users do
  member do
    get 'refazer'
   end
end
end

app/models/user.rb
class User < ApplicationRecord

  validates_presence_of :nome_civil, :email, :licenciatura, :periodo, :matricula

  validates_uniqueness_of :matricula, :email

  validates :pdf_centro, :pdf_campi, :pdf_outros, :status_impressao, presence: false

  validates :status, presence: true

  mount_uploader :avatar, AvatarUploader

  validates_integrity_of  :avatar
  validates_processing_of :avatar
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
     
  enum role: [:normal_user, :moderador, :admin]   
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  private

  def sign_up_params
      params.require(:user).permit(:nome_civil, :nome_social, :email, :matricula, :licenciatura, :periodo, :municipio, :cep, :endereco, :complemento, :numero, :bairro, :telefone, :avatar, :password, :password_confirmation, :nome_da_instituicao, :tipo_da_instituicao, :cnpj, :endereco_da_instituicao, :numero_da_instituicao, :complemento_da_instituicao, :bairro_da_instituicao, :municipio_da_instituicao, :cep_da_instituicao, :telefone_da_instituicao, :representante, :uf, :prefeitura, :estado_da_instituicao)
  end

  def account_update_params
      params.require(:user).permit(:nome_civil, :nome_social, :email, :matricula, :licenciatura, :periodo, :municipio, :cep, :endereco, :complemento, :numero, :bairro, :telefone, :avatar, :password, :password_confirmation, :current_password, :nome_da_instituicao, :tipo_da_instituicao, :cnpj, :endereco_da_instituicao, :numero_da_instituicao, :complemento_da_instituicao, :bairro_da_instituicao, :municipio_da_instituicao, :cep_da_instituicao, :telefone_da_instituicao, :representante, :apolice, :uf, :prefeitura, :estado_da_instituicao)
  end

  protected

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% if defined?(current_user) %>
<div class="d-flex align-items-center justify-content-center">
  <h1>Estágio Curricular Supervisionado</h1>
</div>

<div class="d-flex align-items-center justify-content-center">
  <%= image_tag("DirlicOficial.png", size: "220x220", :alt => "logo estágio curricular supervisonado") -%>   
</div>
<br>

<div class="card">
  <div class="card-header">
    <h3>Usuários</h3>
  </div>

  <br>

  <%= form_tag(users_path, method: :get, class: "form-group") do %>
    <div class="form-group row">
      <div class="col-md-6">
        <%= text_field_tag :nome_civil, params[:nome_civil], class: "form-control", placeholder: 'Nome do aluno' %>
      </div>

      <div class="col-md-4">
        <%= select_tag :licenciatura, options_for_select([["Ciências da Natureza", "Ciências da Natureza"],  ["Educação Física", "Educação Física"], ["Geografia", "Geografia"], ["Letras: Português e Literaturas", "Letras: Português e Literaturas"], ["Matemática", "Matemática"], ["Teatro", "Teatro"]], params[:licenciatura]), prompt: "Selecione o curso", class: "form-control" %>
      </div>

      <div class="col-md-2 text-right">
        <%= submit_tag "Procurar", class: "btn btn-success" %>
    </div>
    </div>
    <br>
    <div class="form-group row">
      <div class="col-md-6">
        <%= text_field_tag :matricula, params[:matricula], class: "form-control", placeholder: 'Matrícula do aluno' %>
      </div>

      <div class="col-md-2">
        <%= select_tag :periodo, options_for_select([["1.º", "1.º"],  ["2.º", "2.º"], ["3.º", "3.º"], ["4.º", "4.º"], ["5.º", "5.º"], ["6.º", "6.º"], ["7.º", "7.º"], ["8.º", "8.º"]], params[:periodo]), prompt: "Selecione o período", class: "form-control" %>
      </div>

      <div class="col-md-2">
        <%= select_tag :finalizacao, options_for_select([["Revisando", "Revisando"],  ["Finalizado", "Finalizado"], ["Negado", "Negado"]], params[:finalizacao]), prompt: "Selecione o status", class: "form-control" %>
      </div>

      <div class="col-md-2">
      <%= link_to "Limpar Pesquisa", users_path, class: "btn btn-secondary"  %>
      </div>
    </div>
  <% end %>
  <br>
  <%= form_with model: @user do |form| %>
    <div class="table-responsive">
      <table class="table table-striped text-center">
        <thead class="thead-dark">
          <tr>
            <th>#</th>
            <th>Perfil</th>
            <th>Nome</th>
            <th>Acessar Perfil</th>
            <th>Enviar E-mail</th>
            <th>Período</th>
            <th>Matrícula</th>
            <th>Licenciatura</th>
            <th>E-mail</th>
            <th>Situação</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td> <!-- Ou outro campo identificador, se preferir -->
              <td>
                <% if user.avatar.url.present? %>
                  <%= image_tag(user.avatar.url, size: "100x100", class: "styleImage") %>
                <% else %>
                  <%= image_tag("DirlicOficial.png", size: "100x100", alt: "logo estágio curricular supervisionado") %>
                <% end %>
              </td>
            <% if user.nome_social.present? && user.nome_social != user.nome_civil && user.nome_social != '--' && user.nome_social != '-' %>
              <td><%= "#{user.nome_civil} (#{user.nome_social})" %></td>
            <% else %>
              <td><%= user.nome_civil %></td>
            <% end %>
              <td>
                <% if user.nome_civil.present? %>
                  <%= link_to "Acessar perfil", user, target: '_blank', class: "btn btn-primary" %>
                <% end %>
              </td>
              <td>
                <% if user.nome_civil.present? %>
                  <%= link_to 'Enviar e-mail', mensagens_path(user_id: user.id), target: '_blank', class: "btn btn-success btn-block" %>
                <% end %>
              </td>
              <td><%= user.periodo %></td>
              <td><%= user.matricula %></td>
              <td><%= user.licenciatura %></td>
              <td><%= user.email %></td>
              <td><%= user.finalizacao %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="pagination">
      <%= will_paginate @users %>
    </div>
  <% end %>
</div>

<div class='contato_dirlic_pdf border mt-4 pt-3 col-md-12'>
  <div class="d-flex align-items-center justify-content-center">
    <%= link_to "Voltar", root_path, class: "btn btn-primary"  %>
  </div> 
  <br>
</div>
<% end %>

app/views/users/show.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Estágio Curricular Supervisionado</h1>
</div>
<div class="d-flex align-items-center justify-content-center">
<% if @user.avatar.url.present? %>
<%= image_tag(@user.avatar.url, size:"220x200", class: "styleImage") %>
	<% else %>
<%= image_tag("DirlicOficial.png", size: "220x220", :alt => "logo estágio curricular supervisonado") -%>  
	<% end %>
</div>
<br>


<div class="card">

	<div class="card-header">
	<% if @user.nome_social.blank? %>
    <li class="list-group-item"><b><h3>Dados da conta de:</b> <%= @user.nome_civil %></h3></li>
    <% else %>
	<li class="list-group-item"><b><h3>Dados da conta de:</b> <%= @user.nome_social %></h3></li>
	<% end %>
	</div>	

  	<div class="row">
    	<div class="col-md-12 ">
			<ul class="list-group">
			<% if @user.role == "normal_user" %>
			<li class=list-group-item><%= link_to "NOVO PREENCHIMENTO", refazer_user_path(:id => @user.id, :action => "refazer"), data: { controller: 'alert', "user-id" => @user.id}, :class => 'btn btn-secondary refazer-btn'  %></td>--- Só clicar após APAGAR todos os PDFs do aluno!</li>
				<% end %>
				<li class=list-group-item><%= link_to 'Enviar e-mail', mensagens_path(:user_id => @user.id), :target => '_blank', :class => "btn btn-success btn-block" %></li>
				<% if @user.nome_social.blank? %>
        		<li class="list-group-item"><b>Nome Civil:</b> <%= @user.nome_civil %></li>
           		 <% else %>
				<li class="list-group-item"><b>Nome Civil:</b> <%= @user.nome_civil %></li>
				<li class="list-group-item"><b>Nome Social:</b> <%= @user.nome_social %></li>
				<% end %>
				<li class="list-group-item"><b>E-mail:</b> <%= @user.email %></li>
				<li class="list-group-item"><b>Licenciatura:</b> <%= @user.licenciatura %></li>
				<li class="list-group-item"><b>Período:</b> <%= @user.periodo %></li>
				<li class="list-group-item"><b>Matrícula:</b> <%= @user.matricula %></li>
				<li class="list-group-item"><b>Status:</b> <%= @user.finalizacao %></li>
				<li class="list-group-item"><b>Cadastrado em:</b> <%= @user.created_at.strftime("%d/%m/%Y - %H:%M:%S") %></li>
				<li class="list-group-item"><b>Atualizado em:</b> <%= @user.updated_at.strftime("%d/%m/%Y - %H:%M:%S") %></li>
				<div class="card-header">
				<% if @user.nome_social.blank? %>
				<li class="list-group-item"><b><h3>Dados da Instituição Concedente de:</b> <%= @user.nome_civil %></h3></li>
				<% else %>
				<li class="list-group-item"><b><h3>Dados da Instituição Concedente de:</b> <%= @user.nome_social %></h3></li>
				<% end %>	
				</div>
				<li class="list-group-item"><b>Nome da Instituição:</b> <%= @user.nome_da_instituicao %></li>
				<li class="list-group-item"><b>Tipo da Instituição:</b> <%= @user.tipo_da_instituicao %></li>
				<li class="list-group-item"><b>CNPJ:</b> <%= @user.cnpj %></li>
				<li class="list-group-item"><b>Endereço da Instituição:</b> <%= @user.endereco_da_instituicao %></li>
				<li class="list-group-item"><b>Número da Instituição:</b> <%= @user.numero_da_instituicao %></li>
				<li class="list-group-item"><b>Complemento da Instituição:</b> <%= @user.complemento_da_instituicao %></li>
				<li class="list-group-item"><b>Bairro da Instituição:</b> <%= @user.bairro_da_instituicao %></li>
				<li class="list-group-item"><b>Município da Instituição:</b> <%= @user.municipio_da_instituicao %></li>
				<li class="list-group-item"><b>CEP da Instituição:</b> <%= @user.cep_da_instituicao %></li>
				<li class="list-group-item"><b>Telefone da Instituição:</b> <%= @user.telefone_da_instituicao %></li>
				<li class="list-group-item"><b>Estado da Instituição:</b> <%= @user.estado_da_instituicao %></li>
				<% if not @user.representante.blank? %>
				<li class="list-group-item"><b>Representada por:</b> <%= @user.representante %></li>
				<% else %>
				<% end %>
			</ul>
		</div>
	</div>

	<div class="card-footer text-muted">
        <div class="col-sm-12">
        	<div class="text-center">
          		
          		<%= link_to "Voltar", root_path, :class => "btn btn-primary"  %>
        	</div>
        </div>
  	</div>  
</div>