config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "welcome#index"
  resources :mensagens do
    collection do
      get 'enviadas'
    end
  end
  get "/welcome", to: "welcome#index"

  get 'users/index'
  get 'users/show'


  #Routes do Sistema de Estágio
  get 'estagio_welcome/locus'

  get 'estagio_welcome/index'
  post 'estagio_welcome/index'

  get 'estagio_welcome/pendente'
  post 'estagio_welcome/pendente'

  get 'estagio_welcome/edit'
  post 'estagio_welcome/edit'

  get 'estagio_welcome/update'
  post 'estagio_welcome/update'

  get 'estagio_welcome/historico'
  post 'estagio_welcome/historico'

  get 'estagio_welcome/status_impressao'
  post 'estagio_welcome/status_impressao'

  get 'estagio_welcome/pdf_visualiza'

  get 'relatorio_centro/index'
  
  get 'relatorio_aditivocentro/index'

  get 'relatorio_campiaditivo/index'

  get 'relatorio_estadualaditivo/index'

  get 'relatorio_municipalouparticularaditivo/index'

  get 'relatorio_campi/index'

  get 'relatorio_publico/index'

  get 'carta_apresentacao/index'
  get 'carta_apresentacao/edit'

  get 'carta_apresentacao/create'
  post 'carta_apresentacao/create'

  get 'carta_apresentacao/edit'
  post 'carta_apresentacao/edit'

  get 'carta_apresentacao/update'
  post 'carta_apresentacao/update'

  get 'relatorio_particular/index'
  get 'relatorio_particular/edit'

  get 'relatorio_particular/update'
  post 'relatorio_particular/update'

  get 'relatorio_particular/create'
  post 'relatorio_particular/create'

  get 'relatorio_naoformal/index'
  get 'relatorio_naoformal/edit'

  get 'relatorio_naoformal/create'
  post 'relatorio_naoformal/create'

  get 'relatorio_naoformal/edit'
  post 'relatorio_naoformal/edit'

  get 'relatorio_naoformal/update'
  post 'relatorio_naoformal/update'

  get 'relatorio_centro/create'
  post 'relatorio_centro/create'

  get 'relatorio_centro/edit'
  post 'relatorio_centro/edit'

  get 'relatorio_aditivocentro/create'
  post 'relatorio_aditivocentro/create'

  get 'relatorio_aditivocentro/edit'
  post 'relatorio_aditivocentro/edit'

  get 'relatorio_aditivocentro/update'
  post 'relatorio_aditivocentro/update'

  get 'relatorio_campiaditivo/create'
  post 'relatorio_campiaditivo/create'

  get 'relatorio_campiaditivo/edit'
  post 'relatorio_campiaditivo/edit'

  get 'relatorio_estadualaditivo/create'
  post 'relatorio_estadualaditivo/create'

  get 'relatorio_estadualaditivo/edit'
  post 'relatorio_estadualaditivo/edit'

  get 'relatorio_estadualaditivo/update'
  post 'relatorio_estadualaditivo/update'

  get 'relatorio_centro/update'
  post 'relatorio_centro/update'

  get 'relatorio_municipalouparticularaditivo/update'
  post 'relatorio_municipalouparticularaditivo/update'

  get 'relatorio_municipalouparticularaditivo/create'
  post 'relatorio_municipalouparticularaditivo/create'

  get 'relatorio_municipalouparticularaditivo/edit'
  post 'relatorio_municipalouparticularaditivo/edit'

  get 'relatorio_campi/create'
  post 'relatorio_campi/create'

  get 'relatorio_campi/edit'
  post 'relatorio_campi/edit'

  get 'relatorio_campi/update'
  post 'relatorio_campi/update'

  get 'relatorio_publico/create'
  post 'relatorio_publico/create'

  get 'relatorio_publico/edit'
  post 'relatorio_publico/edit'

  get 'relatorio_publico/update'
  post 'relatorio_publico/update'

 
  get 'pdf_geral/carta_apresentacao'
  get 'pdf_geral/particular'
  get 'pdf_geral/publico'
  get 'pdf_geral/centro'
  get 'pdf_geral/campi'
  get 'pdf_geral/naoformal'
  get 'pdf_geral/publico'
  get 'pdf_geral/aditivocentro'
  get 'pdf_geral/campiaditivo'
  get 'pdf_geral/estadualaditivo'
  get 'pdf_geral/municipalouparticularaditivo'

  get 'pdf_geral/update_aditivocentro'
  post 'pdf_geral/update_aditivocentro'

  get 'pdf_geral/update_campiaditivo'
  post 'pdf_geral/update_campiaditivo'

  get 'pdf_geral/update_estadualaditivo'
  post 'pdf_geral/update_estadualaditivo'

  get 'pdf_geral/update_municipalouparticularaditivo'
  post 'pdf_geral/update_municipalouparticularaditivo'
  
  get 'pdf_geral/update_particular'
  post 'pdf_geral/update_particular'

  get 'pdf_geral/update_publico'
  post 'pdf_geral/update_publico'

  get 'pdf_geral/update_carta'
  post 'pdf_geral/update_carta'

  get 'pdf_geral/update_centro'
  post 'pdf_geral/update_centro'

  get 'pdf_geral/update_campi'
  post 'pdf_geral/update_campi'

  get 'pdf_geral/update_naoformal'
  post 'pdf_geral/update_naoformal'

  #delete cartaapresentacao
  get 'delete_carta_apresentacao/:user_id', to: 'carta_apresentacao#destroy', as: 'delete_carta_apresentacao'
  #get 'delete_carta_apresentacao/delete_by_matricula/:matricula_aluno', to: 'carta_apresentacao#destroy_by_matricula', as: 'delete_carta_by_matricula'

  #deletes relats
  get '/delete_relat_centro/:user_id', to: 'relatorio_centro#destroy', as: 'delete_relat_centro'
  get '/delete_relat_campi/:user_id', to: 'relatorio_campi#destroy', as: 'delete_relat_campi'
  get '/delete_relat_publico/:user_id', to: 'relatorio_publico#destroy', as: 'delete_relat_publico'
  get '/delete_relat_particular/:user_id', to: 'relatorio_particular#destroy', as: 'delete_relat_particular'
  get '/delete_relat_aditivocentro/:user_id', to: 'relatorio_aditivocentro#destroy', as: 'delete_relat_aditivocentro'
  get '/delete_relat_campiaditivo/:user_id', to: 'relatorio_campiaditivo#destroy', as: 'delete_relat_campiaditivo'
  get '/delete_relat_estadualaditivo/:user_id', to: 'relatorio_estadualaditivo#destroy', as: 'delete_relat_estadualaditivo'
  get '/delete_relat_municipalouparticularaditivo/:user_id', to: 'relatorio_municipalouparticularaditivo#destroy', as: 'delete_relat_municipalouparticularaditivo'


  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords' }
  
 resources :users do
  member do
    get 'liberar'
   end
end

resources :users do
  member do
    get 'refazer'
   end
end
end

app/controllers/mensagens_controller.rb
class MensagensController < ApplicationController
    before_action :set_mensagem, only: [:show]
    before_action :authenticate_user!
    # GET /mensagens
    # GET /mensagens.json
    def index
      @mensagens = Mensagem.where(destinatario_id: params[:user_id]).paginate(page: params[:page])
    end
  
    # GET /mensagens/1
    # GET /mensagens/1.json
    def show
    session[:nome_user] = params['nome_civil']
    end
  
    # GET /mensagens/new
    def new
      @mensagem = Mensagem.new
      @aluno = User.find(params[:user_id])
      @mensagem.destinatario_id = @aluno.id
    end
  
    # POST /mensagens
    # POST /mensagens.json
    def create
      @mensagem = Mensagem.new(mensagem_params)
      @mensagem.remetente_id = current_user.id
  
      respond_to do |format|
        if @mensagem.save
          format.html { redirect_to @mensagem, notice: 'Mensagem enviada com sucesso!' }
          format.json { render :show, status: :created, location: @mensagem }
          ApplicationMailer.mensagem_enviada(@mensagem).deliver
        else
          format.html { render :new }
          format.json { render json: @mensagem.errors, status: :unprocessable_entity }
        end
      end
    end

    def enviadas
      if params[:nome_search].present? || params[:matricula_search].present?
        query = User.all
        query = query.where('nome_civil LIKE ?', "%#{params[:nome_search]}%") if params[:nome_search].present?
        query = query.where('matricula LIKE ?', "%#{params[:matricula_search]}%") if params[:matricula_search].present?
    
        user_ids = query.pluck(:id)
    
        @mensagens_enviadas = Mensagem.where(destinatario_id: user_ids).order(created_at: :desc).paginate(page: params[:page])
      else
        @mensagens_enviadas = Mensagem.order(created_at: :desc).paginate(page: params[:page])
      end
    end
    
  

    private
      def set_mensagem
        @mensagem = Mensagem.find(params[:id])
      end
  
      def mensagem_params
        params.require(:mensagem).permit(:texto, :remetente_id, :destinatario_id)
      end
  end

app/helpers/mensagens_helper.rb
module MensagensHelper
end

app/views/mensagens/_form.html.erb
<%= form_with(model: mensagem, local: true) do |form| %>
  <% if mensagem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mensagem.errors.count, "erro(s)") %> Mensagem não pôde ser enviada!</h2>

      <ul>
      <% mensagem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :destinatario_id %>
  <%= form.hidden_field :remetente_id %>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Aluno(a)</label>
    <div class="col-sm-10">
   <% if @aluno.nome_social.present? && @aluno.nome_social != @aluno.nome_civil && @aluno.nome_social != '--' && @aluno.nome_social != '-' %>
  <%= @aluno.nome_civil %> (<%= @aluno.nome_social %>)
  <% else %>
    <%= @aluno.nome_civil %>
  <% end %>


    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">E-mail</label>
    <div class="col-sm-10">
      <%= @aluno.email %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label text-danger">Texto*</label>
    <div class="col-sm-10">
      <%= form.cktext_area :texto, required: true, rows: 5, class: 'form-control', placeholder: 'Digite o texto do e-mail.' %>
    </div>
  </div>

  <div class="card-footer text-muted">
    <div class="col-sm-12">
      <div class="text-center">
        <%= form.submit  "Enviar", :class => "btn btn-success" %>
        <%= link_to "Voltar", mensagens_path(:user_id => params[:user_id]), :class => "btn btn-primary"  %>
      </div>
    </div>
  </div>     

<% end %>

app/views/mensagens/enviadas.html.erb
<div class="d-flex align-items-center justify-content-center">
  <%= image_tag("DirlicOficial.png", size: "220x220", alt: "logo estágio curricular supervisionado") %>   
</div><br>

<div class="card">
  <div class="card-header">
    <h3>Mensagens Enviadas</h3>
    <%= form_with(url: enviadas_mensagens_path, method: :get, local: true, class: "form-inline") do %>
      <div class="form-group mb-2">
        <%= text_field_tag :nome_search, params[:nome_search], placeholder: "Buscar pelo nome do destinatário", class: "form-control" %>
      </div>
      <div class="form-group mb-2">
        <%= text_field_tag :matricula_search, params[:matricula_search], placeholder: "Buscar pela matrícula do destinatário", class: "form-control" %>
      </div>
      <button type="submit" class="btn btn-primary mb-2">Buscar</button>
      <button type="reset" class="btn btn-secondary mb-2" onclick="window.location.href='<%= enviadas_mensagens_path %>';">Limpar Pesquisa</button>
    <% end %>
  </div>

  <div class="card-body p-3">
    <% @mensagens_enviadas.each do |mensagem| %>
      <p>
        <strong>De:</strong> <%= link_to User.find(mensagem.remetente_id).nome_civil, user_path(mensagem.remetente_id), target: '_blank' %><br>
        <strong>Para:</strong> <%= link_to User.find(mensagem.destinatario_id).nome_civil, user_path(mensagem.destinatario_id), target: '_blank' %><br>
        <strong>Mensagem:</strong> <%= mensagem.texto %><br>
        <strong>Data:</strong> <%= mensagem.created_at.strftime("%d/%m/%Y %H:%M") %>
      </p>
      <hr>
    <% end %>
    <%= will_paginate @mensagens_enviadas %>
  </div>
</div>

app/views/mensagens/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <%= image_tag("DirlicOficial.png", size: "220x220", :alt => "logo estágio curricular supervisonado") -%>   
    </div>
    <div class="container container_estagio">
      <% if current_user.nome_social.blank? %>
        	<li class="list-group-item"><b><h3>Usuário(a):</b> <%= current_user.nome_civil %></h3></li>
            <% else %>
				<li class="list-group-item"><b><h3>Usuário(a):</b> <%= current_user.nome_social %></h3></li>
			<% end %>
      <hr />

<div class="card">

  <div class="card-header"> <h3>E-mails enviados: </h3></div>
    <br>
  <div class="row">
    <div class="formulario_login col-md-6 col-offset-2 ">
      <%= link_to 'Enviar e-mail', new_mensagem_path(user_id: params[:user_id]), :class => "btn btn-success btn-block" %>  
    </div>
  </div>
    <br>
  <div class="table-responsive">
    <table class="table table-striped text-center">
      <thead class="thead-dark ">
        <tr>
          <th>Remetente</th>
          <th>Data</th>
          <th>Ação</th>
        </tr>
      </thead>

      <tbody>
        <% @mensagens.each do |mensagem| %>
          <tr>
            <td><%= mensagem.remetente.nome_civil %></td>
            <td><%= mensagem.created_at.strftime("%d/%m/%Y - %H:%M:%S") %></td>
            <td><%= link_to 'Visualizar', mensagem %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>   

  <div class="card-footer text-muted">
    <div class="col-sm-12">
      <div class="text-center">
        <%= link_to 'Voltar', users_path, :class => "btn btn-primary" %>
      </div>
    </div>
  </div>

</div>

app/views/mensagens/new.html.erb
<div class="d-flex align-items-center justify-content-center">
    <%= image_tag("DirlicOficial.png", size: "220x220", :alt => "logo estágio curricular supervisonado") -%>   
    </div>
    <div class="container container_estagio">
      <% if current_user.nome_social.blank? %>
        	<li class="list-group-item"><b><h3>Usuário(a):</b> <%= current_user.nome_civil %></h3></li>
            <% else %>
				<li class="list-group-item"><b><h3>Usuário(a):</b> <%= current_user.nome_social %></h3></li>
			<% end %>
      <hr />

<div class="card">
	<div class="card-header"> <h3>Enviar e-mail</h3></div>
	<%= render 'form', mensagem: @mensagem %>
</div>

app/views/mensagens/show.html.erb
<div class="d-flex align-items-center justify-content-center">
    <%= image_tag("DirlicOficial.png", size: "220x220", :alt => "logo estágio curricular supervisonado") -%>   
    </div>
    <div class="container container_estagio">
     <% if current_user.nome_social.blank? %>
        	<li class="list-group-item"><b><h3>Usuário(a):</b> <%= current_user.nome_civil %></h3></li>
            <% else %>
				<li class="list-group-item"><b><h3>Usuário(a):</b> <%= current_user.nome_social %></h3></li>
			<% end %>
      <hr />

<div class="card">

  <div class="card-header"> <h3>E-mail enviado</h3></div>

   <div class="row">
      <div class="col-md-12 ">
	    <ul class="list-group">
	    <li class="list-group-item">
        <b>Destinatário:</b>
        <% destinatario = User.find(@mensagem.destinatario_id) %>
        <%= "#{destinatario.nome_civil}#{' (' + destinatario.nome_social + ')' if destinatario.nome_social.present? && destinatario.nome_social != destinatario.nome_civil && destinatario.nome_social != '--' && destinatario.nome_social != '-'}" %>
      </li>
	        <li class="list-group-item"><b>Texto:</b> <%= @mensagem.texto %></li>
	        
	        <li class="list-group-item"><b>Remetente:</b><%= User.find(@mensagem.remetente_id).nome_civil %></li>
	        <li class="list-group-item"><b>Cadastrado em:</b> <%= @mensagem.created_at.strftime("%d/%m/%Y - %H:%M:%S") %></li>
	    </ul>
    </div>
  </div>

  <div class="card-footer text-muted">
    <div class="col-sm-12">
      <div class="text-center">
        <%= link_to "Voltar", users_path, :class => "btn btn-primary"  %>
      </div>
    </div>
  </div>   

</div>